#!/bin/python2

# Generates the bootloader datapage complete with the app checksums.
# Should be written to 0x3fc00.

import struct
import sys
from PyCRC.CRCCCITT import CRCCCITT

with open(sys.argv[1]) as f:
    bytes = f.read()

with open("{}.bootdat".format(sys.argv[1]), 'w') as f:
    f.write(struct.pack('>IIIIIIII', 1, CRCCCITT(version='FFFF').calculate(bytes), 255, len(bytes), 0, 0, 0, 0))
